<?php
$places_in_bangladesh = array (
	'Barisal' =>
		array (
			'Barguna' => array(
				'Amtali',
				'Bamna',
				'Barguna Sadar',
				'Betagi',
				'Patharghata',
				'Taltali',
			),
			'Barisal' => array(
				'Agailjhara',
				'Babuganj',
				'Bakerganj',
				'Banaripara',
				'Gaurnadi',
				'Hizla',
				'Barishal Sadar',
				'Mehendiganj',
				'Muladi',
				'Wazirpur',
			),
			'Bhola' => array(
				'Bhola Sadar',
				'Burhanuddin',
				'Char Fasson',
				'Daulatkhan',
				'Lalmohan',
				'Manpura',
				'Tazumuddin',
			),
			'Jhalokati' => array(
				'Jhalokati Sadar',
				'Kathalia',
				'Nalchity',
				'Rajapur',
			),
			'Patuakhali' => array(
				'Bauphal',
				'Dashmina',
				'Galachipa',
				'Kalapara',
				'Mirzaganj',
				'Patuakhali Sadar',
				'Rangabali',
				'Dumki',
			),
			'Pirojpur' => array(
				'Bhandaria',
				'Kawkhali',
				'Mathbaria',
				'Nazirpur',
				'Pirojpur Sadar',
				'Nesarabad (Swarupkati)',
				'Zianagar',
			),
		),
	'Chittagong' =>
		array (
			'Bandarban' => array(
				'Ali Kadam',
				'Bandarban Sadar',
				'Lama',
				'Naikhongchhari',
				'Rowangchhari',
				'Ruma',
				'Thanchi',
			),
			'Brahmanbaria' => array(
				'Akhaura',
				'Bancharampur',
				'Brahmanbaria Sadar',
				'Kasba',
				'Nabinagar',
				'Nasirnagar',
				'Sarail',
				'Ashuganj',
				'Bijoynagar',
			),
			'Chandpur' => array(
				'Chandpur Sadar',
				'Faridganj',
				'Haimchar',
				'Haziganj',
				'Kachua',
				'Matlab Dakshin',
				'Matlab Uttar',
				'Shahrasti',
			),
			'Chittagong' => array(
				'Anwara',
				'Banshkhali',
				'Boalkhali',
				'Chandanaish',
				'Fatikchhari',
				'Hathazari',
				'Karnaphuli',
				'Lohagara',
				'Mirsharai',
				'Patiya',
				'Rangunia',
				'Raozan',
				'Sandwip',
				'Satkania',
				'Sitakunda',
				'Bandar Thana',
				'Chandgaon Thana',
				'Double Mooring Thana',
				'Kotwali Thana',
				'Pahartali Thana',
				'Panchlaish Thana',
				'Bhujpur Thana',
			),
			'Comilla' => array(
				'Barura',
				'Brahmanpara',
				'Burichang',
				'Chandina',
				'Chauddagram',
				'Daudkandi',
				'Debidwar',
				'Homna',
				'Laksam',
				'Muradnagar',
				'Nangalkot',
				'Cumilla Adarsha Sadar',
				'Meghna',
				'Titas',
				'Monohargonj',
				'Cumilla Sadar Dakshin',
			),
			'Cox\'s Bazar' => array(
				'Chakaria',
				'Cox\'s Bazar Sadar',
				'Kutubdia',
				'Maheshkhali',
				'Ramu',
				'Teknaf',
				'Ukhia',
				'Pekua',
			),
			'Feni' => array(
				'Chhagalnaiya',
				'Daganbhuiyan',
				'Feni Sadar',
				'Parshuram',
				'Sonagazi',
				'Fulgazi',
			),
			'Khagrachhari' => array(
				'Dighinala',
				'Khagrachhari',
				'Lakshmichhari',
				'Mahalchhari',
				'Manikchhari',
				'Matiranga',
				'Panchhari',
				'Ramgarh',
			),
			'Lakshmipur' => array(
				'Lakshmipur Sadar',
				'Raipur',
				'Ramganj',
				'Ramgati',
				'Kamalnagar',
			),
			'Noakhali' => array(
				'Begumganj',
				'Noakhali Sadar',
				'Chatkhil',
				'Companiganj',
				'Hatiya',
				'Senbagh',
				'Sonaimuri',
				'Subarnachar',
				'Kabirhat',
			),
			'Rangamati' => array(
				'Bagaichhari',
				'Barkal',
				'Kawkhali (Betbunia)',
				'Belaichhari',
				'Kaptai',
				'Juraichhari',
				'Langadu',
				'Naniyachar',
				'Rajasthali',
				'Rangamati Sadar',
			),
		),
	'Dhaka' =>
		array (
			'Dhaka' => array(
				'Dhamrai',
				'Dohar',
				'Keraniganj',
				'Nawabganj',
				'Savar',
				'Tejgaon Circle',
			),
			'Faridpur' => array(
				'Alfadanga',
				'Bhanga',
				'Boalmari',
				'Charbhadrasan',
				'Faridpur Sadar',
				'Madhukhali',
				'Nagarkanda',
				'Sadarpur',
				'Saltha',
			),
			'Gazipur' => array(
				'Gazipur Sadar',
				'Kaliakair',
				'Kaliganj',
				'Kapasia',
				'Sreepur',
			),
			'Gopalganj' => array(
				'Gopalganj Sadar',
				'Kashiani',
				'Kotalipara',
				'Muksudpur',
				'Tungipara',
			),
			'Kishoreganj' => array(
				'Austagram',
				'Bajitpur',
				'Bhairab',
				'Hossainpur',
				'Itna',
				'Karimganj',
				'Katiadi',
				'Kishoreganj Sadar',
				'Kuliarchar',
				'Mithamain',
				'Nikli',
				'Pakundia',
			),
			'Madaripur' => array(
				'Rajoir',
				'Madaripur Sadar',
				'Kalkini',
				'Shibchar',
			),
			'Manikganj' => array(
				'Daulatpur',
				'Ghior',
				'Harirampur',
				'Manikgonj Sadar',
				'Saturia',
				'Shivalaya',
				'Singair',
			),
			'Munshiganj' => array(
				'Gazaria',
				'Lohajang',
				'Munshiganj Sadar',
				'Sirajdikhan',
				'Sreenagar',
				'Tongibari',
			),
			'Narayanganj' => array(
				'Araihazar',
				'Bandar',
				'Narayanganj Sadar',
				'Rupganj',
				'Sonargaon',
			),
			'Narsingdi' => array(
				'Narsingdi Sadar',
				'Belabo',
				'Monohardi',
				'Palash',
				'Raipura',
				'Shibpur',
			),
			'Rajbari' => array(
				'Baliakandi',
				'Goalandaghat',
				'Pangsha',
				'Rajbari Sadar',
				'Kalukhali',
			),
			'Shariatpur' => array(
				'Bhedarganj',
				'Damudya',
				'Gosairhat',
				'Naria',
				'Shariatpur Sadar',
				'Zajira',
				'Shakhipur',
			),
			'Tangail' => array(
				'Gopalpur',
				'Basail',
				'Bhuapur',
				'Delduar',
				'Ghatail',
				'Kalihati',
				'Madhupur',
				'Mirzapur',
				'Nagarpur',
				'Sakhipur',
				'Dhanbari',
				'Tangail Sadar',
			),
		),
	'Khulna' =>
		array (
			'Bagerhat' => array(
				'Bagerhat Sadar',
				'Chitalmari',
				'Fakirhat',
				'Kachua',
				'Mollahat',
				'Mongla',
				'Morrelganj',
				'Rampal',
				'Sarankhola',
			),
			'Chuadanga' => array(
				'Alamdanga',
				'Chuadanga Sadar',
				'Damurhuda',
				'Jibannagar',

			),
			'Jessore' => array(
				'Abhaynagar',
				'Bagherpara',
				'Chaugachha',
				'Jhikargachha',
				'Keshabpur',
				'Jashore Sadar',
				'Manirampur',
				'Sharsha',
			),
			'Jhenaidah' => array(
				'Harinakunda',
				'Jhenaidah Sadar',
				'Kaliganj',
				'Kotchandpur',
				'Maheshpur',
				'Shailkupa',
			),
			'Khulna' => array(
				'Batiaghata',
				'Dacope',
				'Dumuria',
				'Dighalia',
				'Koyra',
				'Paikgachha',
				'Phultala',
				'Rupsha',
				'Terokhada',
				'Daulatpur Thana',
				'Khalishpur Thana',
				'Khan Jahan Ali Thana',
				'Kotwali Thana',
				'Sonadanga Thana',
				'Harintana Thana',
			),
			'Kushtia' => array(
				'Bheramara',
				'Daulatpur',
				'Khoksa',
				'Kumarkhali',
				'Kushtia Sadar',
				'Mirpur',
			),
			'Magura' => array(
				'Magura Sadar',
				'Mohammadpur',
				'Shalikha',
				'Sreepur',
			),
			'Meherpur' => array(
				'Gangni',
				'Meherpur Sadar',
				'Mujibnagar',
			),
			'Narail' => array(
				'Kalia',
				'Lohagara',
				'Narail Sadar',
				'Naragati Thana',
			),
			'Satkhira' => array(
				'Assasuni',
				'Debhata',
				'Kalaroa',
				'Kaliganj',
				'Satkhira Sadar',
				'Shyamnagar',
				'Tala',
			),
		),
	'Mymensingh' =>
		array (
			'Jamalpur' => array(
				'Baksiganj',
				'Dewanganj',
				'Islampur',
				'Jamalpur Sadar',
				'Madarganj',
				'Melandaha',
				'Sarishabari',
			),
			'Mymensingh' => array(
				'Trishal',
				'Dhobaura',
				'Fulbaria',
				'Gaffargaon',
				'Gauripur',
				'Haluaghat',
				'Ishwarganj',
				'Mymensingh Sadar',
				'Muktagachha',
				'Nandail',
				'Phulpur',
				'Bhaluka',
				'Tara Khanda',
			),
			'Netrakona' => array(
				'Atpara',
				'Barhatta',
				'Durgapur',
				'Khaliajuri',
				'Kalmakanda',
				'Kendua',
				'Madan',
				'Mohanganj',
				'Netrokona Sadar',
				'Purbadhala',
			),
			'Sherpur' => array(
				'Jhenaigati',
				'Nakla',
				'Nalitabari',
				'Sherpur Sadar',
				'Sreebardi',
			),
		),
	'Rajshahi' =>
		array (
			'Bogra' => array(
				'Adamdighi',
				'Bogura Sadar',
				'Dhunat',
				'Dhupchanchia',
				'Gabtali',
				'Kahaloo',
				'Nandigram',
				'Sariakandi',
				'Shajahanpur',
				'Sherpur',
				'Shibganj',
				'Sonatola',
			),
			'Chapainawabganj' => array(
				'Bholahat',
				'Gomastapur',
				'Nachole',
				'Nawabganj Sadar',
				'Shibganj',
			),
			'Joypurhat' => array(
				'Akkelpur',
				'Joypurhat Sadar',
				'Kalai',
				'Khetlal',
				'Panchbibi',
			),
			'Naogaon' => array(
				'Atrai',
				'Badalgachhi',
				'Manda',
				'Dhamoirhat',
				'Mohadevpur',
				'Naogaon Sadar',
				'Niamatpur',
				'Patnitala',
				'Porsha',
				'Raninagar',
				'Sapahar',
			),
			'Natore' => array(
				'Bagatipara',
				'Baraigram',
				'Gurudaspur',
				'Lalpur',
				'Natore Sadar',
				'Singra',
				'Naldanga',
			),
			'Pabna' => array(
				'Atgharia',
				'Bera',
				'Bhangura',
				'Chatmohar',
				'Faridpur',
				'Ishwardi',
				'Pabna Sadar',
				'Santhia',
				'Sujanagar',
			),
			'Rajshahi' => array(
				'Bagha',
				'Bagmara',
				'Charghat',
				'Durgapur',
				'Godagari',
				'Mohanpur',
				'Paba',
				'Puthia',
				'Tanore',
			),
			'Sirajganj' => array(
				'Belkuchi',
				'Chauhali',
				'Kamarkhanda',
				'Kazipur',
				'Raiganj',
				'Shahjadpur',
				'Sirajganj Sadar',
				'Tarash',
				'Ullahpara',
			),
		),
	'Rangpur' =>
		array (
			'Dinajpur' => array(
				'Birampur',
				'Birganj',
				'Biral',
				'Bochaganj',
				'Chirirbandar',
				'Phulbari',
				'Ghoraghat',
				'Hakimpur',
				'Kaharole',
				'Khansama',
				'Dinajpur Sadar',
				'Nawabganj',
				'Parbatipur',
			),
			'Gaibandha' => array(
				'Phulchhari',
				'Gaibandha Sadar',
				'Gobindaganj',
				'Palashbari',
				'Sadullapur',
				'Sughatta',
				'Sundarganj',
			),
			'Kurigram' => array(
				'Bhurungamari',
				'Char Rajibpur',
				'Chilmari',
				'Phulbari',
				'Kurigram Sadar',
				'Nageshwari',
				'Rajarhat',
				'Raomari',
				'Ulipur',
			),
			'Lalmonirhat' => array(
				'Aditmari',
				'Hatibandha',
				'Kaliganj',
				'Lalmonirhat Sadar',
				'Patgram',
			),
			'Nilphamari' => array(
				'Dimla',
				'Domar',
				'Jaldhaka',
				'Kishoreganj',
				'Nilphamari Sadar',
				'Saidpur',
			),
			'Panchagarh' => array(
				'Atwari',
				'Boda',
				'Debiganj',
				'Panchagarh Sadar',
				'Tetulia',
			),
			'Rangpur' => array(
				'Badarganj',
				'Gangachhara',
				'Kaunia',
				'Rangpur Sadar',
				'Mithapukur',
				'Pirgachha',
				'Pirganj',
				'Taraganj',
			),
			'Thakurgaon' => array(
				'Baliadangi',
				'Haripur',
				'Pirganj',
				'Ranisankail',
				'Thakurgaon Sadar',
			),
		),
	'Sylhet' =>
		array (
			'Habiganj' => array(
				'Ajmiriganj',
				'Bahubal',
				'Baniyachong',
				'Chunarughat',
				'Habiganj Sadar',
				'Lakhai',
				'Madhabpur',
				'Nabiganj',
				'Sayestaganj',
			),
			'Moulvibazar' => array(
				'Barlekha',
				'Juri',
				'Kamalganj',
				'Kulaura',
				'Moulvibazar Sadar',
				'Rajnagar',
				'Sreemangal',
			),
			'Sunamganj' => array(
				'Bishwamvarpur',
				'Chhatak',
				'Dakshin Sunamganj',
				'Derai',
				'Dharamapasha',
				'Dowarabazar',
				'Jagannathpur',
				'Jamalganj',
				'Sullah',
				'Sunamganj Sadar',
				'Tahirpur',
			),
			'Sylhet' => array(
				'Balaganj',
				'Beanibazar',
				'Bishwanath',
				'Companigonj',
				'Dakshin Surma',
				'Fenchuganj',
				'Golapganj',
				'Gowainghat',
				'Jaintiapur',
				'Kanaighat',
				'Osmani Nagar',
				'Sylhet Sadar',
				'Zakiganj',
			),
		),
);
